imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: fos_user.yml }
  - { resource: doctrine_extensions.yml }
  - { resource: "@LogicBundle/Resources/config/config.yml" }
  - { resource: "@AdminBundle/Resources/config/config.yml" }
  - { resource: "@ProduccionBundle/Resources/config/services.yml" }
parameters:
  locale: es
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
framework:
  #esi:             ~
  translator:      { fallbacks: ["%locale%"] }
  secret:          "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form:            ~
  csrf_protection: ~
  validation:      { enable_annotations: true }
  #serializer:      { enable_annotations: true }
  templating:
    engines: ['twig']
    #assets_version: SomeVersionScheme
  default_locale:  "%locale%"
  trusted_hosts:   ~
  trusted_proxies: ~
  session:
    # handler_id set to null will use default session handler from php.ini
    handler_id:  ~
  fragments:       ~
  http_method_override: true

# Twig Configuration
twig:
  form_themes:
    - '@SonataCore/Form/datepicker.html.twig'
  globals:
    kernelRootDir: %kernel.root_dir%
  debug:            "%kernel.debug%"
  strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   '%database_driver%'
        host:     '%database_host%'
        port:     '%database_port%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
        charset:  UTF8
        mapping_types:
          sysname: string
      produccion:
        driver:   '%database_driver2%'
        host:     '%database_host2%'
        port:     '%database_port2%'
        dbname:   '%database_name2%'
        user:     '%database_user2%'
        password: '%database_password2%'
        charset:  UTF8
        mapping_types:
          sysname: string

  orm:
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        mappings:
          ApplicationSonataUserBundle:  ~
          LogicBundle: ~
      produccion:
        connection: produccion
        mappings:
          ProduccionBundle: ~

# Swiftmailer Configuration
swiftmailer:
  transport:  smtp
  encryption: ssl
  auth_mode:  login
  host:       smtp.gmail.com
  username:   oscar.estupinan@ito-software.com
  password:   1t0s0ftw4r3*

assetic:
  debug:          '%kernel.debug%'
  use_controller: '%kernel.debug%'
  filters:
    cssrewrite: ~

nelmio_api_doc: ~


hwi_oauth:
  firewall_names: [secured_area]
  resource_owners:
    my_custom:
      type:                oauth2
      client_id:           <client_id>
      client_secret:       <client_secret>
      access_token_url:    https://path.to/oauth/v2/token
      authorization_url:   https://path.to/oauth/v2/authorize
      infos_url:           https://path.to/api/user
      scope:               "read"
      user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
      paths:
        identifier: id
        nickname:   username
        realname:   fullname

guzzle:
  clients: ~

knp_snappy:
  pdf:
    enabled:    true
    binary:     '%kernel.root_dir%/../lib/wkhtmltopdf'
    #        options:
    #            javascript-delay: 3000
    options:    []
  image:
    enabled:    true
    binary:     '%kernel.root_dir%/../lib/wkhtmltopdf'
    options:    []