<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping\AttributeOverrides;
use Doctrine\ORM\Mapping\AttributeOverride;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */

/**
 * User
 *
 * @ORM\Table(name="Usuario")
 * @ORM\Entity(repositoryClass="Application\Sonata\UserBundle\Entity\Repository\UserRepository")
 * @AttributeOverrides({
 *     @AttributeOverride(name="email",
 *         column=@ORM\Column(
 *             name="UsuMail",
 *             type="string",
 *             length=255,
 *             unique=false
 *         )
 *     ),
 *     @AttributeOverride(name="emailCanonical",
 *         column=@ORM\Column(
 *             name="email_canonical",
 *             type="string",
 *             length=255,
 *             unique=false
 *         )
 *     ),
 *     @AttributeOverride(name="username",
 *         column=@ORM\Column(
 *             name="UsuCodigo",
 *             type="string",
 *             length=20
 *         )
 *     ),
 *     @AttributeOverride(name="password",
 *         column=@ORM\Column(
 *             name="UsuClave",
 *             type="string",
 *             length=255,
 *             nullable=false
 *         )
 *     ),
 *     @AttributeOverride(name="enabled",
 *         column=@ORM\Column(
 *             name="UsuEstado",
 *             type="boolean"
 *         )
 *     ),
 *     @AttributeOverride(name="roles",
 *         column=@ORM\Column(
 *             name="roles",
 *             type="array",
 *             nullable=true
 *         )
 *     )
 * })
 */
class User extends BaseUser
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", name="UsuNombre",length=100)
     */
    protected $usuNombre;
    /**
     * @ORM\Column(type="string", name="UsuNumeroTelefonica",length=255, nullable=true)
     */
    protected $usuNumeroTelefonica;

    /**
     * @ORM\Column(type="string", name="UsuMobil",length=20)
     */
    protected $usuMobil;
    /**
     * @ORM\Column(type="string", name="UsuPhone",length=20)
     */
    protected $usuPhone;
    /**
     * @ORM\Column(type="string", name="UsuExt",length=10,nullable=true)
     */
    protected $usuExt;


    /**
     * Set usuNombre.
     *
     * @param string $usuNombre
     *
     * @return User
     */
    public function setUsuNombre($usuNombre)
    {
        $this->usuNombre = $usuNombre;

        return $this;
    }

    /**
     * Get usuNombre.
     *
     * @return string
     */
    public function getUsuNombre()
    {
        return $this->usuNombre;
    }

    /**
     * Set usuNumeroTelefonica.
     *
     * @param string|null $usuNumeroTelefonica
     *
     * @return User
     */
    public function setUsuNumeroTelefonica($usuNumeroTelefonica = null)
    {
        $this->usuNumeroTelefonica = $usuNumeroTelefonica;

        return $this;
    }

    /**
     * Get usuNumeroTelefonica.
     *
     * @return string|null
     */
    public function getUsuNumeroTelefonica()
    {
        return $this->usuNumeroTelefonica;
    }

    /**
     * Set usuMobil.
     *
     * @param string $usuMobil
     *
     * @return User
     */
    public function setUsuMobil($usuMobil)
    {
        $this->usuMobil = $usuMobil;

        return $this;
    }

    /**
     * Get usuMobil.
     *
     * @return string
     */
    public function getUsuMobil()
    {
        return $this->usuMobil;
    }

    /**
     * Set usuPhone.
     *
     * @param string $usuPhone
     *
     * @return User
     */
    public function setUsuPhone($usuPhone)
    {
        $this->usuPhone = $usuPhone;

        return $this;
    }

    /**
     * Get usuPhone.
     *
     * @return string
     */
    public function getUsuPhone()
    {
        return $this->usuPhone;
    }

    /**
     * Set usuExt.
     *
     * @param string|null $usuExt
     *
     * @return User
     */
    public function setUsuExt($usuExt = null)
    {
        $this->usuExt = $usuExt;

        return $this;
    }

    /**
     * Get usuExt.
     *
     * @return string|null
     */
    public function getUsuExt()
    {
        return $this->usuExt;
    }
}
